# Generated by Django 4.0.3 on 2022-03-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSV_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='CSV_files', verbose_name='CSV_файл')),
            ],
            options={
                'verbose_name': 'CSV_файл',
                'verbose_name_plural': 'CSV_файлы',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=48, verbose_name='Код')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('level_one', models.CharField(blank=True, max_length=48, null=True, verbose_name='Уровень1')),
                ('level_two', models.CharField(blank=True, max_length=48, null=True, verbose_name='Уровень2')),
                ('level_three', models.CharField(blank=True, max_length=48, null=True, verbose_name='Уровень3')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('price_cp', models.PositiveIntegerField(default=0, verbose_name='ЦенаСП')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('properties', models.TextField(blank=True, null=True, verbose_name='Поля свойств')),
                ('join_shopping', models.TextField(blank=True, null=True, verbose_name='Совместная покупка')),
                ('measurement_unit', models.CharField(max_length=15, verbose_name='Единица измерения')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='image_item', verbose_name='Картинка')),
                ('is_view_main', models.BooleanField(default=False, verbose_name='Вывод на главной')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
